name: AigrisCollectors CI

on:
  push:
  pull_request:

jobs:
  run_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
  
      - name: Run build script
        run: |
          cd CI
          sh build.sh

