name: AigrisCollectors CI

on:
  push:
  pull_request:

env:
  DIRECTORY_TO_EXAMINE: lib

jobs:
  run_build:
    runs-on: ubuntu-latest

    steps:
      - name: Install cppcheck
        run: sudo apt install cppcheck -y

      - uses: actions/checkout@v3

      - name: Run build script
        run: |
          cd CI
          sh build.sh
